// Typed, validated adapter for the static graph projection artifact (plan 0030, C).
// The artifact is generated by `python -m application.projection.export_cli` and committed
// under public/graph/projection.json. Validation is intentionally strict: a shape drift
// between the Python exporter and this reader must fail at load with a clear message, not
// surface as `undefined` deep in a component. The schema version is checked so an
// incompatible artifact is reported rather than half-rendered.

export const SCHEMA_VERSION = "0030.graph-projection.2";

export type Predicate =
  | "is"
  | "causes"
  | "expresses"
  | "requires"
  | "contrasts_with"
  | "makes"
  | "creates"
  | "undoes"
  | "other";
export type Polarity = "affirmed" | "negated";
export type Mode = "assertion" | "normative" | "conditional" | "question";
export type Attribution = "course" | "ego" | "others" | "hypothetical";
export type ExclusionReason =
  | "missing_object"
  | "subject_not_drawable"
  | "object_not_drawable";

export interface EvidenceSegments {
  before: string;
  clause: string;
  after: string;
  evidence_start: number;
  evidence_end: number;
}

export interface PassageRef {
  source_id: string;
  book: string;
  chapter: number;
  verse: number | null;
  section: number | null;
  paragraph: number | null;
  edition: string;
  evidence: EvidenceSegments;
}

export interface GraphNode {
  node_id: string;
  label: string;
  entity_id: string | null;
  expressions: string[];
}

export interface GraphEdge {
  claim_id: string;
  source_node_id: string;
  target_node_id: string;
  subject: string;
  object: string;
  predicate: Predicate;
  verb_phrase: string;
  polarity: Polarity;
  mode: Mode;
  attribution: Attribution;
  source_id: string;
  evidence_start: number;
  evidence_end: number;
}

export interface NonProjectable {
  claim_id: string;
  subject: string;
  object: string | null;
  predicate: Predicate;
  verb_phrase: string;
  polarity: Polarity;
  mode: Mode;
  attribution: Attribution;
  reason: ExclusionReason;
  source_id: string;
  evidence_start: number;
  evidence_end: number;
}

export interface ArtifactMetadata {
  schema_version: string;
  content_hash: string;
  claim_count: number;
  resolution_entity_count: number;
  source_count: number;
}

export interface GraphArtifact {
  metadata: ArtifactMetadata;
  nodes: GraphNode[];
  edges: GraphEdge[];
  non_projectable: NonProjectable[];
  passages: PassageRef[];
}

export class ArtifactError extends Error {}

// A key that joins an edge/non-projectable claim to its passage. Mirrors the Python
// exporter's dedup key (source_id + evidence span): one passage per distinct quoted span.
export const passageKey = (sourceId: string, start: number, end: number): string =>
  `${sourceId}:${start}:${end}`;

const isObject = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null;

const str = (o: Record<string, unknown>, k: string): string => {
  const v = o[k];
  if (typeof v !== "string") throw new ArtifactError(`expected string field "${k}"`);
  return v;
};

const num = (o: Record<string, unknown>, k: string): number => {
  const v = o[k];
  if (typeof v !== "number") throw new ArtifactError(`expected number field "${k}"`);
  return v;
};

const numOrNull = (o: Record<string, unknown>, k: string): number | null => {
  const v = o[k];
  if (v === null) return null;
  if (typeof v !== "number") throw new ArtifactError(`expected number|null field "${k}"`);
  return v;
};

const strOrNull = (o: Record<string, unknown>, k: string): string | null => {
  const v = o[k];
  if (v === null) return null;
  if (typeof v !== "string") throw new ArtifactError(`expected string|null field "${k}"`);
  return v;
};

const arr = (o: Record<string, unknown>, k: string): unknown[] => {
  const v = o[k];
  if (!Array.isArray(v)) throw new ArtifactError(`expected array field "${k}"`);
  return v;
};

// Parse + validate a raw JSON value into a GraphArtifact. Throws ArtifactError on any
// shape mismatch so the page can show its invalid-artifact state rather than crash.
export const parseArtifact = (raw: unknown): GraphArtifact => {
  if (!isObject(raw)) throw new ArtifactError("artifact is not an object");

  const meta = raw.metadata;
  if (!isObject(meta)) throw new ArtifactError("missing metadata");
  const schema = str(meta, "schema_version");
  if (schema !== SCHEMA_VERSION) {
    throw new ArtifactError(
      `incompatible schema ${schema}; this build expects ${SCHEMA_VERSION}`,
    );
  }

  const nodes = arr(raw, "nodes").map((n): GraphNode => {
    if (!isObject(n)) throw new ArtifactError("node is not an object");
    return {
      node_id: str(n, "node_id"),
      label: str(n, "label"),
      entity_id: strOrNull(n, "entity_id"),
      expressions: arr(n, "expressions").map((e) => {
        if (typeof e !== "string") throw new ArtifactError("expression is not a string");
        return e;
      }),
    };
  });

  const edges = arr(raw, "edges").map((e): GraphEdge => {
    if (!isObject(e)) throw new ArtifactError("edge is not an object");
    return {
      claim_id: str(e, "claim_id"),
      source_node_id: str(e, "source_node_id"),
      target_node_id: str(e, "target_node_id"),
      subject: str(e, "subject"),
      object: str(e, "object"),
      predicate: str(e, "predicate") as Predicate,
      verb_phrase: str(e, "verb_phrase"),
      polarity: str(e, "polarity") as Polarity,
      mode: str(e, "mode") as Mode,
      attribution: str(e, "attribution") as Attribution,
      source_id: str(e, "source_id"),
      evidence_start: num(e, "evidence_start"),
      evidence_end: num(e, "evidence_end"),
    };
  });

  const non_projectable = arr(raw, "non_projectable").map((n): NonProjectable => {
    if (!isObject(n)) throw new ArtifactError("non_projectable is not an object");
    return {
      claim_id: str(n, "claim_id"),
      subject: str(n, "subject"),
      object: strOrNull(n, "object"),
      predicate: str(n, "predicate") as Predicate,
      verb_phrase: str(n, "verb_phrase"),
      polarity: str(n, "polarity") as Polarity,
      mode: str(n, "mode") as Mode,
      attribution: str(n, "attribution") as Attribution,
      reason: str(n, "reason") as ExclusionReason,
      source_id: str(n, "source_id"),
      evidence_start: num(n, "evidence_start"),
      evidence_end: num(n, "evidence_end"),
    };
  });

  const passages = arr(raw, "passages").map((p): PassageRef => {
    if (!isObject(p)) throw new ArtifactError("passage is not an object");
    const ev = p.evidence;
    if (!isObject(ev)) throw new ArtifactError("passage missing evidence");
    return {
      source_id: str(p, "source_id"),
      book: str(p, "book"),
      chapter: num(p, "chapter"),
      verse: numOrNull(p, "verse"),
      section: numOrNull(p, "section"),
      paragraph: numOrNull(p, "paragraph"),
      edition: str(p, "edition"),
      evidence: {
        before: str(ev, "before"),
        clause: str(ev, "clause"),
        after: str(ev, "after"),
        evidence_start: num(ev, "evidence_start"),
        evidence_end: num(ev, "evidence_end"),
      },
    };
  });

  return {
    metadata: {
      schema_version: schema,
      content_hash: str(meta, "content_hash"),
      claim_count: num(meta, "claim_count"),
      resolution_entity_count: num(meta, "resolution_entity_count"),
      source_count: num(meta, "source_count"),
    },
    nodes,
    edges,
    non_projectable,
    passages,
  };
};

export const loadArtifact = async (
  url = "/graph/projection.json",
  fetchFn: typeof fetch = fetch,
): Promise<GraphArtifact> => {
  let raw: unknown;
  try {
    const res = await fetchFn(url);
    if (!res.ok) throw new ArtifactError(`artifact fetch failed (${res.status})`);
    raw = await res.json();
  } catch (e) {
    if (e instanceof ArtifactError) throw e;
    throw new ArtifactError("artifact could not be loaded");
  }
  return parseArtifact(raw);
};
